name: ios_launcher
description: "A Liquid Glass iOS 26 inspired Android Launcher built with Flutter."
publish_to: 'none'

version: 1.0.2+9

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
